#!/bin/sh

### BEGIN INIT INFO
# Required-Start: $nginx
# Required-Stop: $nginx
# Default-Start:  345
# Default-Stop: 90
# Short-Description: starman for adbass
# Description: starman server for adbass-corporare
### END INIT INFO

# Start a Plack daemon.
PERL_DIST="/usr/local/perl-dists/perls/perl-5.19.8/bin/"
PATH=$PERL_DIST:/bin:/usr/bin:/sbin:/usr/sbin
DAEMON="$PERL_DIST/plackup"
NAME="dancer-pearlbee"
APP_DIR="/var/www/PearlBee"
LOG_DIR="${APP_DIR}/logs"
SSD=/usr/local/sbin/start-stop-daemon
USERID=www-data
# Defaults
RUN="no"
OPTIONS="-E production -s Starman --worker=2 -l /tmp/${NAME}.sock -R ${APP_DIR}/restart.txt --app ${APP_DIR}/bin/app.pl"
PIDFILE="${LOG_DIR}/$NAME.pid"

#
# These compatibility funcs are here just for sarge backports.
# They will be removed post-etch.
#
log_daemon_msg() {
    echo -n "$1: $2"
}

log_end_msg() {
    if [ $1 -ne 0 ]; then
echo " failed!"
    else
echo "."
    fi
}

[ -f /lib/lsb/init-functions ] && . /lib/lsb/init-functions

if [ "x$UID" != "x0" ]; then
    log_daemon_msg "Need to be root" "$NAME"
    log_end_msg 1
    exit 1
fi


start() {
    cd "${APP_DIR}"
    log_daemon_msg "Starting plack server" "$NAME"
    ${SSD} --background --make-pidfile --start --chuid ${USERID} --quiet --pidfile "$PIDFILE" --exec $DAEMON -- $OPTIONS
    if [ $? != 0 ]; then
	log_end_msg 1
        exit 1
    else
	log_end_msg 0
    fi
}

signal() {
    if [ "$1" = "stop" ]; then
	SIGNAL="TERM"
        log_daemon_msg "Stopping plack server" "$NAME"
    else
    if [ "$1" = "reload" ]; then
	SIGNAL="HUP"
        log_daemon_msg "Reloading plack server" "$NAME"
    else
	echo "ERR: wrong parameter given to signal()"
        exit 1
    fi
    fi
    if [ -f "$PIDFILE" ]; then
	${SSD} --stop --signal $SIGNAL --quiet --pidfile "$PIDFILE"
     if [ $? = 0 ]; then
	log_end_msg 0
     else
	SIGNAL="KILL"
        ${SSD} --stop --signal $SIGNAL --quiet --pidfile "$PIDFILE"
        if [ $? != 0 ]; then
		log_end_msg 1
                [ $2 != 0 ] || exit 0
        else
		rm "$PIDFILE"
                log_end_msg 0
        fi
    fi
    if [ "$SIGNAL" = "KILL" ]; then
    	rm -f "$PIDFILE"
    fi
    else
      	log_end_msg 0
    fi
}

case "$1" in
    start)
    start
    ;;

    force-start)
    start
    ;;

    stop)
        signal stop 0
    ;;

    force-stop)
    signal stop 0
    ;;

    reload)
    signal reload 0
    ;;

    force-reload|restart)
    signal stop 1
    sleep 2
    start
    ;;

    *)
    echo "Usage: /etc/init.d/$NAME {start|force-start|stop|force-stop|reload|restart|force-reload}"
    exit 1
    ;;
esac

exit 0
